name: Postman CI Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman + Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run collection/CaseStudyCollection.postman_collection.json \
          -e collection/NewEnvironment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman-report.html

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html