name: Postman Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run collection/CaseStudyCollection.postman_collection.json \
          -e collection/NewEnvironment.json